export {default as Watch} from '../assets/watch.png'
export {default as HeadPhone} from '../assets/head-phone.png'
export {default as Iphone11} from '../assets/iphone-11.png'
export { default as Iphone11_white} from '../assets/iphone-11-white.png'
export { default as MacPro16} from '../assets/macbook-pro-16.png'
export { default as Iphone11_red} from '../assets/iphone-11-red.png'
export { default as Iphone12_pink} from '../assets/iphone-12-purple.png'
export { default as Iphone13_blue} from '../assets/iphone-13-blue.png'
export { default as DellGrey } from '../assets/dell-grey.png'
export { default as Iphone13_green } from '../assets/iphone-13-grey.png'
export { default as Iphone13_grey } from '../assets/iphone-13-grey.png'
export { default as SamsungGalaxyNote21 } from '../assets/samsung-21.png'
export { default as feSamsungGalaxyS21 } from '../assets/samsung-21s.png'
export { default as DellWhite } from '../assets/dell-white.png'